### ISSUE TITLE
Extremely laggy scrolling since rows aren't being cached

### ISSUE THREAD

**Issue by guidedways** [aciodev/Stellar#7]
I noticed the table view data delegates instantiate and return a new row each time a cellView is requested. Because of this, scrolling is painfully slow and the memory consumption rises the moment you scroll a few long threads.

<img width="270" alt="Screenshot 2021-02-21 at 01 25 09@2x" src="https://user-images.githubusercontent.com/202437/108608949-e748a400-73e3-11eb-8256-220819d26a4b.png">

**Comment by aciodev** [comment]
Hi and thanks for using Stellar.

To be clear you're referring to [this](https://github.com/aciodev/Stellar/blob/main/Stellar/UI/PostList/PostList.swift#L304) as the source of the memory leak.

Normally in iOS we'd use 

```swift
tableView.dequeueReusableCell(withIdentifier: "postCell", for: indexPath) as! PostListCell
```

However, if I recall correctly, I had troubles using a similar method in NSTableView which required an .XIB file. I'll take a look into this right now.

I had a suspicion this would trigger memory issues due to not reusing cells. Thanks for confirming.

**Comment by guidedways** [comment]
@aciodev That's it. This, including any other code where it returns a row (SearchPopOver.swift, PostList.swift, AwardsPopOver.swift etc):

`func tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?, row: Int) -> NSView?`

Yes it's unfortunate that on macOS you have to have a dummy nib in order to be able to create these programmatically. There's no exception to the rule for now. Hopefully SwiftUI will change things when it becomes mainstream in the next few years. For now we're stuck.

**Comment by guidedways** [comment]
The following may suffice as a fix (see: https://stackoverflow.com/questions/19464136/view-based-nsoutlineview-without-nib):

```
    let viewIdentifier = NSUserInterfaceItemIdentifier(rawValue: "PostListCell")
    if let cell = tableView.makeView(withIdentifier: viewIdentifier, owner: nil) {
      return cell
    }
    
    let pvc = PostListCell(postViewer: postViewer, childData: self.childData[row], votingColorProfile: votingColorProfile, mediaHandler: mediaHandler) // HERE: Index out of range
    
    pvc.identifier = viewIdentifier
    
    if focusedCell == row {
      previousCell?.titleField.textColor = .systemGray
      previousCell = pvc
      previousCell?.titleField.textColor = .orange
    }
    return pvc
```

**Comment by guidedways** [comment]
You may still have to clear / reset the actual cell when it's reused though, as I see other glitches in the left panel after making this change. The PostViewer also suffers from extreme lag, may need caching separately.

**Comment by guidedways** [comment]
Also realized `PostListCell` should be changed to become a subclass of `NSTableCellView` instead

**Comment by aciodev** [comment]
Playing around with the .XIB file as a dummy placeholder. Refactoring as well to use NSTableCellView. Going to see if this stacks up compared to the previous implementation.

**Comment by guidedways** [comment]
I see a difference at my end, however I can see it's still stacking up memory usage as I scroll the post list. It seems to be caching icons / images perhaps or there's some other memory leak. Instruments with leaks / zombies turned on may immediately point out the culprit

**Comment by aciodev** [comment]
Worth noting that the [image cache](https://github.com/aciodev/Stellar/blob/main/Stellar/AppDelegate.swift#L23-L33) framework I use retains 300 MB of images in memory before clearing out old entries using an LRU.

**Comment by guidedways** [comment]
That might explain it :)

**Comment by guidedways** [comment]
@aciodev Sorry - bad place to be doing this, but just connected you on LinkedIn. Would be great to connect.

**Comment by aciodev** [comment]
Strange. When using the following (sourced from your provided link and Raywenderlich's site, the print statement for "Using cached" is never called. I've created an XIB for the view and haven't noticed a cell being reused. Especially when I scroll aggressively. Will continue testing and update this issue.

```swift
fileprivate extension NSUserInterfaceItemIdentifier {
    static let postListCellView = NSUserInterfaceItemIdentifier("PostListCellView")
}
```

```swift
    func tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?, row: Int) -> NSView? {
        if let cell = makeView(withIdentifier: .postListCellView, owner: nil) {
            print("Using cached")
            return cell
        }
        
        print("New object")
        let pvc = PostListCell(postViewer: postViewer, childData: self.childData[row], votingColorProfile: votingColorProfile, mediaHandler: mediaHandler) // HERE: Index out of range
        if focusedCell == row {
            previousCell?.titleField.textColor = .systemGray
            previousCell = pvc
            previousCell?.titleField.textColor = .orange
        }
        return pvc
    }
```

**Comment by guidedways** [comment]
You're missing one key statement, see my code - 

`pvc.identifier = viewIdentifier`

You need to assign it an identifier.

**Comment by aciodev** [comment]
Ahh, that was silly. Thanks. I can now see the issue you mentioned earlier about previous cell data bugging out the view (e.g. the height of the row being calculated incorrectly.)

Also, I've accepted your connection. Always great to connect with others.

**Comment by aciodev** [comment]
Completely overhauled PostListCell.swift with your recommendations and big rewrites. At a cursory glance, things appear to be much better. Please re-open if the issue persists.

I'll be hunting down memory leaks which are related to this.

My thinking is through dependency injection, there are hard references keeping certain things alive that should be garbage collected.
